spring:
  application:
    name: alstarboard

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ? ???? ???? localhost:???/????????????????????&???&????
    url: jdbc:mysql://localhost:3386/alstarboard?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # ? mySQL ???, ????. ?? ??? ??? ? ?? ??
    username: root
    password: 1234
    hikari: # connection? caching??. ??? ?? ?? ??? ??? ??.
      maximum-pool-size: 5
      minimum-idle: 5
      connection-timeout: 30000 # 30 sec
      idle_timeout: 600000
      max_lifetime: 1800000 # ?? idle? 2?

  # jpa : jpa? mybatis? ???????? ??? ???? ????. (? ? ??)
  # ?? ??? ???? ?? ??? ?? ???? ?? ??? ??? ???? ?.
  # ?? ??? jpa? ?? ??. ??? ??? ?? ??? ???? ??? ?? ????. ?? ?? ?? ??? ?? ??.
  # ??? ??? ??? ??. ?? ?? email.password ???? ?? ????? jpa? ???? ???? ??? ????? ??.
  # ?? ??? ? ?? ??? ?????, ?? jpa? ??? ? ??? ?? ???? ???. ??? ??? ??????? ?? ? ?.
  jpa:
    hibernate:
      # ??? ?? ? ???? ??
      ddl-auto: update

    # jpa? ??? sql?? ? ??? ??? ??? ? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_sql_comments: true

  message:
    encoding: UTF-8

# mybatis : ??? ?? ???? ??? ??, ?????? ??? ? ?? ??, ?? ??? ?? ???. ??? ??? ?? ???? ???? ? ?? ??.
mybatis:
  mapper-locations: classpath.mapper/*.xml
  type-aliases-package: com.example.alstarboard.domain #src/main/java ?? ?? ??? ??

  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080 # 8080 ????? ??? ?? x

logging:
  level:
    root: INFO
    com.example.alstarboard: DEBUG
